### ISSUE TITLE
🐞 [Bug]: `wsl-manjaro` package broken after upstream `ManjaroWSL2` repo rename

### ISSUE THREAD

**Issue by Rikj000** [kamack38/packages#5]
### Package

`wsl-manjaro`

### Describe the bug

@sileshn renamed the `ManjaroWSL` repo to [`ManjaroWSL2`](https://github.com/sileshn/ManjaroWSL2),   
which currently breaks the installation of the `wsl-manjaro` package through chocolatey.

Also, the package/checksums are a few releases behind.

### Expected behavior

The `wsl-manjaro` package installing successfully on the latest version.

### Relevant log output

```shell
[ERROR] - ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/sileshn/ManjaroWSL/releases/download/20220414/ManjaroWSL.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
```

### Desktop

- Package Version: `2022.04.14`
- Chocolatey Version: `1.2.1`

**Comment by kamack38** [comment]
The packages should be fixed now. At least when it comes to update. I don't have how to check if the package itself correctly installs.

**Comment by Rikj000** [comment]
Thanks for the update @kamack38!

For chocolatey, the package install failed, since following returns nothing:
```powershell
choco list -l | findstr.exe manjaro
```

However, even though Chocolatey gave an error,   
Manjaro is installed on my system now! :tada: 

Here are my CLI output + `chocolatey.log` file,   
after a 2nd install attempt, which also failed for choco:
[Choco-Install-CLI.log](https://github.com/kamack38/packages/files/10798659/Choco-Install-CLI.log)
[chocolatey.log](https://github.com/kamack38/packages/files/10798660/chocolatey.log)
