### ISSUE TITLE
[Bug]: Onefetch Chocolatey package not being updated

### ISSUE THREAD

**Issue by piraces** [kamack38/packages#6]
### Package

onefetch

### Describe the bug

Latest Chocolatey version is 2.12.0. when the latest one from source is 2.15.1 (as of the time of writing this issue).
Seems that some versions are being lost in the Chocolatey page... maybe the `AU` update process is not running correctly?

### Expected behavior

OneFetch in Chocolatey must show latest version (or at least be in the moderation queue) v2.15.1.
Now it's showing a previous one.

### Desktop

- Package Version [e.g. 1.15.64]: 2.12.0
- Chocolatey Version [e.g. 0.11.3]: 1.3.0

**Comment by kamack38** [comment]
The package should now be correctly updated. Its new version should be pushed to chocolatey during the closest update (around 21:30 CEST).

**Comment by piraces** [comment]
Thanks for the quick fix! 👍
